AWSTemplateFormatVersion: 2010-09-09
Description: This template has the security group with an ec2 instance
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: This is sample security group create using CFT
      VpcId: vpc-0746efe0010e45be5
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance: #name of the resource
    Type: AWS::EC2::Instance #give the type of the resource, here we have given EC2-Instance
    Properties: #now give the properties
      ImageId: ami-0e83be366243f524a
      InstanceType: t2.micro
      KeyName: NewKeyPair
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - Ref: InstanceSecurityGroup
          SubnetId: subnet-028cc28001feb5aab
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: true
            VolumeSize: 8

Outputs:
  SecurityGroupId:
    Description: SecurityGroup Id
    Value:
      Ref: InstanceSecurityGroup